language: java

jdk:
  - oraclejdk8

script: "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"

services:
  - redis
  - mongodb

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
